/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sonuan_xxxxjni_MainActivity */

#ifndef _Included_com_sonuan_xxxxjni_MainActivity
#define _Included_com_sonuan_xxxxjni_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sonuan_xxxxjni_MainActivity
 * Method:    jniForHelloWorld
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sonuan_xxxxjni_MainActivity_jniForHelloWorld
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
